kind: Secret
apiVersion: v1
metadata:
  name: postgres-secret
  labels:
    app.kubernetes.io/name: "postgres"
    app.kubernetes.io/component: postgresql-server
type: Opaque
data:
  password: cnhuOFRzY1p4dTNrYVA0c3FCZW4=
