apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    app: flask
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: flask
  type: LoadBalancer
  loadBalancerIP: "34.105.210.145"
